spring:
  datasource:
    url: jdbc:mysql://mysql-statefulset-0.mysql-service:3306/notifications
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
    show-sql: true
server:
  port: 9092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
